### ISSUE TITLE
Internal an External Infrastructure 

### ISSUE THREAD

**Issue by imbadjoe1993** [ibm-cloud-docs/ghededicated#4]
Sometimes i can't stayed logged in once logged in... Itll still say I have to sign in... Recently it said this User can't log in to my fast food app

**Comment by acolleen** [comment]
@ibmbadjoe1993 thanks for your feedback. Can you please provide a little more information so that we can investigate your issue? Which topic in the GitHub Enterprise on IBM Cloud documentation did you have questions about?

**Comment by acolleen** [comment]
Closing - there isn't any actionable information in the issue and the user hasn't responded to a request for more information.
